### ISSUE TITLE
Readme changes

### ISSUE THREAD

**Issue by solojavier** [softcraft/bike-store#7]
- [x] I think blog administration can be moved to the first stage
- [x] Split `Stock control` and `accounting control` in 2 different stages
- [x] I don't understand what do you mean in stage 3....
- [x] I think we could split `products` section from stage 1 and move it to a different one... and we could do some preparatory work for the store.

**Comment by ghost** [comment]
what i mean in the stage 3 is generate the logins for the system. Create the login to administrator and to employee

**Comment by ghost** [comment]
i don't understand the point 4 je :/  what do you recommend for this part?

**Comment by solojavier** [comment]
What I mean in 4. is that we take out from stage 1. `products` and make it it's own stage.
